### ISSUE TITLE
Error installing aldryn-blog

### ISSUE THREAD

**Issue by dossan** [divio/django-cms-tutorial#57]
I am following the tutorial from the django-cms official website, but I am a problem installing _aldryn-blog_ using _pip_. This is the output when I try to install aldryn-blog:

```Collecting aldryn-blog
  Using cached aldryn-blog-0.4.6.tar.gz
Collecting django-taggit<0.12 (from aldryn-blog)
  Using cached django_taggit-0.11.2-py2.py3-none-any.whl
Collecting django-filer (from aldryn-blog)
  Using cached django-filer-0.9.9.tar.gz
Collecting django-select2 (from aldryn-blog)
  Using cached Django-Select2-4.2.2.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/gz/0xcqjr9x45lg8rqg256dtmwh0000gn/T/pip-build-i9jmsxh9/django-select2```

I am on the virtual environment, and since I quite newbie to django-cms, I really don't know what could be the problem, except that the output is talking about a _<string>_ file...

**Comment by omnibrain** [comment]
I had the same problem on Arch Linux.

I "solved" this problem by switching to Python2.7. Assuming you're using virtualenvwrapper, create an env with 

```
$ mkvirtualenv -p /usr/bin/python2.7 yourenvname
```
switch to your newly created python2.7 virtualenv with

```
$ workon yourenvname
```

and then you can install aldryn-blog as described in the tutorial with

```
$ pip install aldryn-blog
```

Hope that helps.
